[archive]
build_output_dir = 'Built'
archive_location = '\\us-aus-hilbuild\builds\lru-architecture\custom devices\udp'

[projects.cd]
path = 'Source\UDP-Custom-Device Custom Device.lvproj'

[[build.steps]]
name = 'Configuration Library'
type = 'lvBuildSpec'
project = '{cd}'
target = 'My Computer'
build_spec = 'Configuration Release'

[[build.steps]]
name = 'Engine Libraries'
type = 'lvBuildSpecAllTargets'
project = '{cd}'
build_spec = 'Engine Release'